aruco_dictionary_name: "DICT_ARUCO_ORIGINAL"
aruco_marker_side_length: 0.144 #0.144
camera_calibration_parameters_filename: "src/handeye_calibration/camera_info.yaml"
image_topic: "/camera/camera/color/image_raw" #/camera/image_raw
aruco_marker_name: "aruco_marker"
calculated_camera_optical_frame_name: "camera_color_optical_frame" #calculated_camera_link_optical
marker_data_file_name: "src/handeye_calibration/marker_data.yaml"
image_filename: "src/handeye_calibration/marker_pose_{pose_count}.jpg"
robot_data_file_name: "src/handeye_calibration/robot_data.yaml"
handeye_result_file_name: "src/handeye_calibration/handeye_result.yaml"
handeye_result_profile_file_name: "src/handeye_calibration/handeye_result_profile.yaml"

base_link: "base_link"
ee_link: "link6"
world_frame: "world"